spring.application.name=desafio.flashsale

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/flashsale
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true